### ISSUE TITLE
Crash when dragging the window into another screen

### ISSUE THREAD

**Issue by moodyhunter** [hypengw/Qcm#17]
Qcm Version: 1.0.2

```
Name            : qcm
Version         : 1.0.2-2
```

Qcm receives a SIGSEGV when it enters a new screen:

backtrace:

```
qrc:/Qcm/App/qml/page/PlaylistDetailPage.qml:26:17: QML ColumnLayout: Possible anchor loop detected on horizontal anchor.

Thread 1 "Qcm" received signal SIGSEGV, Segmentation fault.
0x00007ffff462840f in QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::get (this=<optimized out>, this=<optimized out>) at /usr/include/qt6/QtCore/qscopedpointer.h:112
warning: Source file is more recent than executable.
112             return d;
(gdb) 
(gdb) bt
#0  0x00007ffff462840f in QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::get (this=<optimized out>, this=<optimized out>) at /usr/include/qt6/QtCore/qscopedpointer.h:112
#1  qGetPtrHelper<QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> > const> (ptr=<optimized out>, ptr=<optimized out>) at /usr/include/qt6/QtCore/qtclasshelpermacros.h:79
#2  QQuickItem::d_func (this=<optimized out>) at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickitem.h:481
#3  QQuickItem::flags (this=<optimized out>) at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickitem.cpp:6955
#4  updatePixelRatioHelper (item=0x0, pixelRatio=pixelRatio@entry=2) at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:383
#5  0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#6  0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#7  0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#8  0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#9  0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#10 0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#11 0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#12 0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#13 0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#14 0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#15 0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#16 0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=2)
    at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#17 0x00007ffff4628459 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=2) at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:390
#18 0x00007ffff462c0a7 in QQuickWindow::physicalDpiChanged (this=<optimized out>) at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:401
#19 0x00007ffff4634614 in QQuickWindow::event (this=<optimized out>, event=<optimized out>) at /usr/src/debug/qt6-declarative/qtdeclarative-everywhere-src-6.6.2/src/quick/items/qquickwindow.cpp:1568
#20 0x00007ffff2f39818 in QCoreApplication::notifyInternal2 (receiver=0x555555d39ca0, event=0x7fffffffd7a0)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.2/src/corelib/kernel/qcoreapplication.cpp:1121
#21 0x00007ffff2f3985d in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.2/src/corelib/kernel/qcoreapplication.cpp:1539
#22 0x00007ffff35c9547 in QWindowPrivate::updateDevicePixelRatio (this=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.2/src/gui/kernel/qwindow.cpp:1386
#23 0x00007ffff35da85c in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.2/src/gui/kernel/qwindowsysteminterface.cpp:1109
#24 0x00007ffff39b26c4 in userEventSourceDispatch (source=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.2/src/gui/platform/unix/qeventdispatcher_glib.cpp:38
#25 0x00007ffff130d199 in g_main_dispatch (context=0x7fffdc000f00) at ../glib/glib/gmain.c:3344
#26 0x00007ffff136c3bf in g_main_context_dispatch_unlocked (context=0x7fffdc000f00) at ../glib/glib/gmain.c:4152
#27 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffdc000f00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4217
#28 0x00007ffff130c712 in g_main_context_iteration (context=0x7fffdc000f00, may_block=1) at ../glib/glib/gmain.c:4282
#29 0x00007ffff31739c4 in QEventDispatcherGlib::processEvents (this=0x555555d0d190, flags=...) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.2/src/corelib/kernel/qeventdispatcher_glib.cpp:393
#30 0x00007ffff2f43d6e in QEventLoop::processEvents (flags=..., this=0x7fffffffda90) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.2/src/corelib/kernel/qeventloop.cpp:100
#31 QEventLoop::exec (this=0x7fffffffda90, flags=...) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.2/src/corelib/kernel/qeventloop.cpp:182
#32 0x00007ffff2f3c2b8 in QCoreApplication::exec () at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.2/src/corelib/global/qflags.h:74
#33 0x0000555555605903 in ??? ()
#34 0x00007ffff3c43cd0 in __libc_start_call_main (main=main@entry=0x555555603e30, argc=argc@entry=1, argv=argv@entry=0x7fffffffe0b8) at ../sysdeps/nptl/libc_start_call_main.h:58
#35 0x00007ffff3c43d8a in __libc_start_main_impl (main=0x555555603e30, argc=1, argv=0x7fffffffe0b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe0a8)
    at ../csu/libc-start.c:360
#36 0x000055555561e9b5 in ??? ()
```

System Info

```
Operating System: Arch Linux 
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.2-arch2-1 (64-bit)
Graphics Platform: Wayland
Processors: 32 × 13th Gen Intel® Core™ i9-13900HX
Memory: 62.6 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4050 Laptop GPU/PCIe/SSE2
Manufacturer: LENOVO
Product Name: 82WK
System Version: Legion Y9000P IRX8
```

**Comment by hypengw** [comment]
fixed.

**Comment by moodyhunter** [comment]
Out of curiosity, which commit contains the fix?

**Comment by hypengw** [comment]
https://github.com/hypengw/QmlMaterial/commit/4da38bb94b95d63d218d5e9049c77cd79a8985ab

**Comment by moodyhunter** [comment]
Indeed fixed :) Thanks
