### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sakarie9** [hypengw/Qcm#7]
```
  [1]    117170 segmentation fault (core dumped)  Qcm

  Stack trace of thread 114872:
  #0  0x00007f09d21c372a _ZN22QGuiApplicationPrivate10setPaletteERK8QPalette (libQt6Gui.so.6 + 0x1c372a)
  #1  0x00007f09d21c5033 _ZN22QGuiApplicationPrivate13updatePaletteEv (libQt6Gui.so.6 + 0x1c5033)
  #2  0x00007f09d21b6c6e _ZN22QGuiApplicationPrivate4initEv (libQt6Gui.so.6 + 0x1b6c6e)
  #3  0x00007f09d21b0f8f _ZN15QGuiApplicationC2ERiPPci (libQt6Gui.so.6 + 0x1b0f8f)
  #4  0x000055f05795889f n/a (Qcm + 0x24989f)
  #5  0x000055f05777600e n/a (Qcm + 0x6700e)
  #6  0x00007f09d1223ad0 n/a (libc.so.6 + 0x23ad0)
  #7  0x00007f09d1223b8a __libc_start_main (libc.so.6 + 0x23b8a)
  #8  0x000055f057779f05 n/a (Qcm + 0x6af05)
  
  Stack trace of thread 114873:
  #0  0x00007f09d131c3cf __poll (libc.so.6 + 0x11c3cf)
  #1  0x00007f09d0c0e88f n/a (libglib-2.0.so.0 + 0xce88f)
  #2  0x00007f09d0b9f852 g_main_context_iteration (libglib-2.0.so.0 + 0x5f852)
  #3  0x00007f09d1d62509 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x362509)
  #4  0x00007f09d1b401fe _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1401fe)
  #5  0x00007f09d1c3bbdf _ZN7QThread4execEv (libQt6Core.so.6 + 0x23bbdf)
  #6  0x00007f09d3ef13df n/a (libQt6DBus.so.6 + 0x2f3df)
  #7  0x00007f09d1c89701 n/a (libQt6Core.so.6 + 0x289701)
  #8  0x00007f09d129708f n/a (libc.so.6 + 0x9708f)
  #9  0x00007f09d13294b0 n/a (libc.so.6 + 0x1294b0)
  
  Stack trace of thread 114874:
  #0  0x00007f09d1293686 n/a (libc.so.6 + 0x93686)
  #1  0x00007f09d129603e pthread_cond_wait (libc.so.6 + 0x9603e)
  #2  0x00007f09d1c8dc4c _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x28dc4c)
  #3  0x00007f09cd37f131 n/a (libQt6WaylandClient.so.6 + 0x69131)
  #4  0x00007f09d1c89701 n/a (libQt6Core.so.6 + 0x289701)
  #5  0x00007f09d129708f n/a (libc.so.6 + 0x9708f)
  #6  0x00007f09d13294b0 n/a (libc.so.6 + 0x1294b0)
  
  Stack trace of thread 114875:
  #0  0x00007f09d131c3cf __poll (libc.so.6 + 0x11c3cf)
  #1  0x00007f09cd37f1ac n/a (libQt6WaylandClient.so.6 + 0x691ac)
  #2  0x00007f09d1c89701 n/a (libQt6Core.so.6 + 0x289701)
  #3  0x00007f09d129708f n/a (libc.so.6 + 0x9708f)
  #4  0x00007f09d13294b0 n/a (libc.so.6 + 0x1294b0)
  ELF object binary architecture: AMD x86-64
```
- Qcm r55.f39f015-1 in AUR
- Archlinux 6.3.1
- QT6 6.5.0
- Hyprland wayland session

**Comment by Kimiblock** [comment]
> ```
>   [1]    117170 segmentation fault (core dumped)  Qcm
> 
>   Stack trace of thread 114872:
>   #0  0x00007f09d21c372a _ZN22QGuiApplicationPrivate10setPaletteERK8QPalette (libQt6Gui.so.6 + 0x1c372a)
>   #1  0x00007f09d21c5033 _ZN22QGuiApplicationPrivate13updatePaletteEv (libQt6Gui.so.6 + 0x1c5033)
>   #2  0x00007f09d21b6c6e _ZN22QGuiApplicationPrivate4initEv (libQt6Gui.so.6 + 0x1b6c6e)
>   #3  0x00007f09d21b0f8f _ZN15QGuiApplicationC2ERiPPci (libQt6Gui.so.6 + 0x1b0f8f)
>   #4  0x000055f05795889f n/a (Qcm + 0x24989f)
>   #5  0x000055f05777600e n/a (Qcm + 0x6700e)
>   #6  0x00007f09d1223ad0 n/a (libc.so.6 + 0x23ad0)
>   #7  0x00007f09d1223b8a __libc_start_main (libc.so.6 + 0x23b8a)
>   #8  0x000055f057779f05 n/a (Qcm + 0x6af05)
>   
>   Stack trace of thread 114873:
>   #0  0x00007f09d131c3cf __poll (libc.so.6 + 0x11c3cf)
>   #1  0x00007f09d0c0e88f n/a (libglib-2.0.so.0 + 0xce88f)
>   #2  0x00007f09d0b9f852 g_main_context_iteration (libglib-2.0.so.0 + 0x5f852)
>   #3  0x00007f09d1d62509 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x362509)
>   #4  0x00007f09d1b401fe _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1401fe)
>   #5  0x00007f09d1c3bbdf _ZN7QThread4execEv (libQt6Core.so.6 + 0x23bbdf)
>   #6  0x00007f09d3ef13df n/a (libQt6DBus.so.6 + 0x2f3df)
>   #7  0x00007f09d1c89701 n/a (libQt6Core.so.6 + 0x289701)
>   #8  0x00007f09d129708f n/a (libc.so.6 + 0x9708f)
>   #9  0x00007f09d13294b0 n/a (libc.so.6 + 0x1294b0)
>   
>   Stack trace of thread 114874:
>   #0  0x00007f09d1293686 n/a (libc.so.6 + 0x93686)
>   #1  0x00007f09d129603e pthread_cond_wait (libc.so.6 + 0x9603e)
>   #2  0x00007f09d1c8dc4c _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x28dc4c)
>   #3  0x00007f09cd37f131 n/a (libQt6WaylandClient.so.6 + 0x69131)
>   #4  0x00007f09d1c89701 n/a (libQt6Core.so.6 + 0x289701)
>   #5  0x00007f09d129708f n/a (libc.so.6 + 0x9708f)
>   #6  0x00007f09d13294b0 n/a (libc.so.6 + 0x1294b0)
>   
>   Stack trace of thread 114875:
>   #0  0x00007f09d131c3cf __poll (libc.so.6 + 0x11c3cf)
>   #1  0x00007f09cd37f1ac n/a (libQt6WaylandClient.so.6 + 0x691ac)
>   #2  0x00007f09d1c89701 n/a (libQt6Core.so.6 + 0x289701)
>   #3  0x00007f09d129708f n/a (libc.so.6 + 0x9708f)
>   #4  0x00007f09d13294b0 n/a (libc.so.6 + 0x1294b0)
>   ELF object binary architecture: AMD x86-64
> ```
> 
>     * Qcm r55.f39f015-1 in AUR
> 
>     * Archlinux 6.3.1
> 
>     * QT6 6.5.0
> 
>     * Hyprland wayland session

Fully update your system, then try to clone https://aur.archlinux.org/qcm-git.git and run `makepkg -si` manually.

**Comment by xzsk2** [comment]
Tried makepkg, build in clean chroot and build in Github actions, none of them works

**Comment by hypengw** [comment]
Please compile with `-DCMAKE_BUILD_TYPE=Debug`.  
And run with gdb to print backtrace.

**Comment by xzsk2** [comment]
```
Starting program: /tmp/tmpfs/Qcm/build/app/Qcm

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff11ff6c0 (LWP 261472)]
[New Thread 0x7fffea86d6c0 (LWP 261473)]
[New Thread 0x7fffea06c6c0 (LWP 261474)]

Thread 1 "Qcm" received signal SIGSEGV, Segmentation fault.
0x00007ffff5fc372a in QGuiApplicationPrivate::setPalette(QPalette const&) () from /usr/lib/libQt6Gui.so.6
#0  0x00007ffff5fc372a in QGuiApplicationPrivate::setPalette(QPalette const&) () at /usr/lib/libQt6Gui.so.6
#1  0x00007ffff5fc5033 in QGuiApplicationPrivate::updatePalette() () at /usr/lib/libQt6Gui.so.6
#2  0x00007ffff5fb6c6e in QGuiApplicationPrivate::init() () at /usr/lib/libQt6Gui.so.6
#3  0x00007ffff5fb0f8f in QGuiApplication::QGuiApplication(int&, char**, int) () at /usr/lib/libQt6Gui.so.6
#4  0x000055555587dfb7 in SingleApplication::SingleApplication(int&, char**, bool, QFlags<SingleApplication::Mode>, int, QString const&) (this=0x7fffffffda10, argc=@0x7fffffffd9dc: 1, argv=0x7fffffffdb98, allowSecondary=false, options=..., timeout=1000, userData=...) at /tmp/tmpfs/Qcm/third_party/SingleApplication/singleapplication.cpp:40
#5  0x000055555559ea37 in main(int, char**) (argc=1, argv=0x7fffffffdb98) at /tmp/tmpfs/Qcm/app/main.cpp:17
#0  0x00007ffff5fc372a in QGuiApplicationPrivate::setPalette(QPalette const&) () at /usr/lib/libQt6Gui.so.6
#1  0x00007ffff5fc5033 in QGuiApplicationPrivate::updatePalette() () at /usr/lib/libQt6Gui.so.6
#2  0x00007ffff5fb6c6e in QGuiApplicationPrivate::init() () at /usr/lib/libQt6Gui.so.6
#3  0x00007ffff5fb0f8f in QGuiApplication::QGuiApplication(int&, char**, int) () at /usr/lib/libQt6Gui.so.6
#4  0x000055555587dfb7 in SingleApplication::SingleApplication(int&, char**, bool, QFlags<SingleApplication::Mode>, int, QString const&) (this=0x7fffffffda10, argc=@0x7fffffffd9dc: 1, argv=0x7fffffffdb98, allowSecondary=false, options=..., timeout=1000, userData=...) at /tmp/tmpfs/Qcm/third_party/SingleApplication/singleapplication.cpp:40
#5  0x000055555559ea37 in main(int, char**) (argc=1, argv=0x7fffffffdb98) at /tmp/tmpfs/Qcm/app/main.cpp:17
        logger = 0x555555dbff10
        gui_app = {<QGuiApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7ffff66a1240 <QGuiApplication::staticMetaObject>}, stringdata = 0x555555b87a20 <(anonymous namespace)::qt_meta_stringdata_CLASSSingleApplicationENDCLASS>, data = 0x555555b87aa0 <qt_meta_data_CLASSSingleApplicationENDCLASS>, static_metacall = 0x55555587d448 <SingleApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, metaTypes = 0x555555d80700 <qt_incomplete_metaTypeArray<(anonymous namespace)::qt_meta_stringdata_CLASSSingleApplicationENDCLASS_t, QtPrivate::TypeAndForceComplete<SingleApplication, std::integral_constant<bool, true> >, QtPrivate::TypeAndForceComplete<void, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<void, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<unsigned int, std::integral_constant<bool, false> >, QtPrivate::TypeAndForceComplete<QByteArray, std::integral_constant<bool, false> > >>, extradata = 0x0}}, d_ptr = 0x7fffffffda90}
        parser = {d = 0x7fffffffda60}
        verboseOption = {d = {d = 0x7fffffffda20}}
        re = 32767
```
